export const mockEmployees = [
  {
    firstName: "Brianna",
    lastName: "Slyvester",
    dateOfBirth: "09/06/1979",
    startDate: "6/23/2022",
    department: "Legal",
    street: "7 Cardinal Park",
    city: "Washington",
    state: "DC",
    ZipCode: "20535",
  },
  {
    firstName: "Jameson",
    lastName: "Kaygill",
    dateOfBirth: "09/01/1939",
    startDate: "7/6/2022",
    department: "Human Resources",
    street: "1 Meadow Ridge Hill",
    city: "Toledo",
    state: "OH",
    ZipCode: "43656",
  },
  {
    firstName: "Hubert",
    lastName: "Fierro",
    dateOfBirth: "07/06/1990",
    startDate: "9/28/2022",
    department: "Marketing",
    street: "3 Melvin Crossing",
    city: "New York City",
    state: "NY",
    ZipCode: "10203",
  },
  {
    firstName: "Graham",
    lastName: "Klement",
    dateOfBirth: "25/12/2001",
    startDate: "2/27/2022",
    department: "Sales",
    street: "2 Kings Circle",
    city: "Portland",
    state: "OR",
    ZipCode: "97286",
  },
  {
    firstName: "Corrina",
    lastName: "Bruhnicke",
    dateOfBirth: "08/12/1936",
    startDate: "9/23/2021",
    department: "Engineering",
    street: "268 Crest Line Place",
    city: "Charleston",
    state: "SC",
    ZipCode: "29416",
  },
  {
    firstName: "Field",
    lastName: "Huston",
    dateOfBirth: "29/08/1964",
    startDate: "10/2/2022",
    department: "Legal",
    street: "0 Chinook Place",
    city: "Columbus",
    state: "OH",
    ZipCode: "43268",
  },
  {
    firstName: "Estel",
    lastName: "Pidcock",
    dateOfBirth: "24/05/1944",
    startDate: "10/11/2021",
    department: "Legal",
    street: "2 Hoepker Crossing",
    city: "Houston",
    state: "TX",
    ZipCode: "77085",
  },
  {
    firstName: "Sophey",
    lastName: "Britnell",
    dateOfBirth: "21/11/1989",
    startDate: "6/25/2022",
    department: "Sales",
    street: "31234 Hovde Lane",
    city: "Jackson",
    state: "MS",
    ZipCode: "39296",
  },
  {
    firstName: "Gisela",
    lastName: "Dagworthy",
    dateOfBirth: "25/06/1948",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "7460 Moland Street",
    city: "Pittsburgh",
    state: "PA",
    ZipCode: "15255",
  },
  {
    firstName: "Tomlin",
    lastName: "Eliyahu",
    dateOfBirth: "18/11/1944",
    startDate: "9/4/2022",
    department: "Marketing",
    street: "447 Bobwhite Circle",
    city: "Richmond",
    state: "VA",
    ZipCode: "23289",
  },
  {
    firstName: "Esra",
    lastName: "Mathwen",
    dateOfBirth: "27/01/1974",
    startDate: "1/27/2022",
    department: "Human Resources",
    street: "49231 Banding Junction",
    city: "Houston",
    state: "TX",
    ZipCode: "77281",
  },
  {
    firstName: "Devland",
    lastName: "Terrelly",
    dateOfBirth: "02/11/1986",
    startDate: "3/13/2022",
    department: "Legal",
    street: "61 Algoma Avenue",
    city: "Denton",
    state: "TX",
    ZipCode: "76205",
  },
  {
    firstName: "Angelina",
    lastName: "Towndrow",
    dateOfBirth: "24/08/1930",
    startDate: "8/19/2022",
    department: "Legal",
    street: "5739 Drewry Avenue",
    city: "San Francisco",
    state: "CA",
    ZipCode: "94132",
  },
  {
    firstName: "Ginnifer",
    lastName: "Pencott",
    dateOfBirth: "04/02/1938",
    startDate: "12/5/2022",
    department: "Human Resources",
    street: "63070 Judy Drive",
    city: "Anniston",
    state: "AL",
    ZipCode: "36205",
  },
  {
    firstName: "Olivia",
    lastName: "Sarl",
    dateOfBirth: "30/07/1962",
    startDate: "1/11/2023",
    department: "Sales",
    street: "0242 Hazelcrest Terrace",
    city: "Ridgely",
    state: "MD",
    ZipCode: "21684",
  },
  {
    firstName: "Olivette",
    lastName: "Benzi",
    dateOfBirth: "03/09/1937",
    startDate: "11/9/2021",
    department: "Engineering",
    street: "9327 Hansons Circle",
    city: "Austin",
    state: "TX",
    ZipCode: "78710",
  },
  {
    firstName: "Kim",
    lastName: "Coyett",
    dateOfBirth: "10/09/1966",
    startDate: "7/15/2022",
    department: "Sales",
    street: "1493 Tennessee Park",
    city: "Atlanta",
    state: "GA",
    ZipCode: "30323",
  },
  {
    firstName: "Perice",
    lastName: "Cheeke",
    dateOfBirth: "06/11/2003",
    startDate: "10/1/2022",
    department: "Sales",
    street: "29443 Corscot Trail",
    city: "Jacksonville",
    state: "FL",
    ZipCode: "32209",
  },
  {
    firstName: "Constantin",
    lastName: "MacInnes",
    dateOfBirth: "13/04/1993",
    startDate: "11/27/2021",
    department: "Marketing",
    street: "12298 Dayton Plaza",
    city: "Memphis",
    state: "TN",
    ZipCode: "38168",
  },
  {
    firstName: "Cliff",
    lastName: "Manuel",
    dateOfBirth: "29/03/1989",
    startDate: "1/17/2022",
    department: "Sales",
    street: "69248 Thierer Drive",
    city: "Meridian",
    state: "MS",
    ZipCode: "39305",
  },
];
